# Generated by Django 4.2.20 on 2025-05-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/', verbose_name=''),
        ),
    ]
